- name: Add ros repository
  apt_repository:
    repo: deb http://packages.ros.org/ros/ubuntu xenial main
    state: present

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: 421C365BD9FF1F717815A3895523BAEEB01FA116

- name: Update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Add robot user
  user:
    name: robot
    shell: /bin/bash

- name: Add ssh keys
  authorized_key:
    user: robot
    state: present
    key: "https://github.com/{{ item }}.keys"
  with_items:
    - HeMan
    - erik78se

- name: Download robojoy
  git:
    repo: 'https://github.com/erik78se/robojoy.git'
    dest: /home/robot/catkin_ws
  become: yes
  become_user: robot
 
- name: Packages for ros
  apt:
    name: "{{ item }}"
    state: present
    allow_unauthenticated : yes
  with_items:
    - ros-kinetic-teleop-twist-joy
    - ros-kinetic-joy-teleop
    - ros-kinetic-joy
    - ros-kinetic-rosserial-arduino
